monitorrule=name:DP-1,width:1920,height:1080,refresh:180,x:0,y:0
monitorrule=name:DVI-D-1,width:1680,height:1050,refresh:60,x:1920,y:0

source=~/.config/mango/mangoconfs/keybinds.conf
source=~/.cache/wal/mangowm.conf
source=~/.config/mango/mangoconfs/autostart.conf

blur=0

shadows = 0

border_radius=0
no_radius_when_single=0

dim_enable=0
dim_focused_color=0x00000000
dim_unfocused_color=0x00000055

animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=zoom
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
zoom_initial_ratio=0.0
zoom_end_ratio=0.0
fadein_begin_opacity=0.5
fadeout_begin_opacity=1.0
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=350
animation_duration_close=800
animation_duration_focus=0
animation_curve_open=0.46,1.0,0.29,1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.46,1.0,0.29,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadeout=1,1,0,1
animation_curve_opafadein=0.22,1,0.36,1

new_is_master=0
default_mfact=0.65
default_nmaster=1
tag_num=9
smartgaps=0

hotarea_size=5
enable_hotarea=0

no_border_when_single=0
axis_bind_apply_timeout=40
focus_on_activate=1
idleinhibit_ignore_visible=0
idleinhibit_when_fullscreen=0
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focusdir_only_zone_overlap=1
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
float_full_to_top=0
cursor_size=24
drag_tile_to_tile=1
drag_tile_small=1


repeat_rate=30
repeat_delay=250
numlockon=0
xkb_rules_layout=us,ru
xkb_rules_options=grp:alt_shift_toggle

disable_trackpad=1

mouse_natural_scrolling=0

gappih=5
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=3

tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
