# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: SUPER,CTRL,ALT,shift,none


bind=SUPER+SHIFT,r,reload_config
bind=SUPER+SHIFT,y,~/.config/mango/scripts/spicetify-watcher.sh


bind=SUPER,r,spawn,rofi -show drun
bind=SUPER,t,spawn,foot
bind=SUPER,s,spawn,AyuGram
bind=SUPER,e,spawn,nemo
bind=SUPER,w,spawn,firefox
bind=SUPER,a,spawn,spotify
bind=SUPER,d,spawn,discord

bind=SUPER,m,spawn,~/.config/mango/scripts/rofi-wallpaper.sh
bind=SUPER+SHIFT,s,spawn,~/.config/mango/scripts/screenshot.sh
bind=SUPER,v,spawn,sh -c "cliphist list | rofi -dmenu | cliphist decode | wl-copy"

bind=SUPER+SHIFT,z,spawn,sh -c "playerctl previous"
bind=SUPER+SHIFT,x,spawn,sh -c "playerctl play-pause"
bind=SUPER+SHIFT,c,spawn,sh -c "playerctl next"

bind=SUPER+SHIFT,m,quit
bind=SUPER,q,killclient

axisbind=SUPER,UP,viewtoleft
axisbind=SUPER,DOWN,viewtoright

bind=SUPER,Tab,focusstack,next


bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

bind=SUPER,g,toggleglobal,
bind=ALT,Tab,togglejump,
bind=SUPER,space,togglefloating,
bind=ALT,f,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,
bind=SUPER+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
